identifier ::= identifier_start {identifier_start | identifier_extend}

identifier_start ::=
                 letter_uppercase
                 | letter_lowercase
                 | letter_titlecase
                 | letter_modifier
                 | letter_other
                 | number_letter

identifier_extend ::=
                  mark_non_spacing
                  | mark_spacing_combining
                  | number_decimal
                  | punctuation_connector

numeric_literal ::= decimal_literal | based_literal

decimal_literal ::= numeral [.numeral] [exponent]

numeral ::= digit {[underline] digit}

exponent ::= E [+] numeral | E – numeral

digit ::= 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9

based_literal ::= base # based_numeral [.based_numeral] # [exponent]

base ::= numeral

based_numeral ::= extended_digit {[underline] extended_digit}

extended_digit ::= digit | A | B | C | D | E | F

character_literal ::= 'graphic_character'

string_literal ::= "{string_element}"

string_element ::= "" | non_quotation_mark_ graphic_character

comment ::= --{non_end_of_line_character}